"""
Mock adapter for testing workflows without actual agent execution.
"""

import asyncio
from pathlib import Path

from ..utils.logger import get_logger
from .base import AgentAdapter, AgentResult


class MockAdapter(AgentAdapter):
    """
    Mock adapter that simulates agent execution for testing.

    Instead of calling a real agent, it creates placeholder output files.
    """

    def __init__(self, delay: float = 1.0):
        """
        Initialize Mock adapter.

        :param delay: Simulated execution delay in seconds
        """
        self.delay = delay
        self.logger = get_logger()
        self._running = False

    @property
    def name(self) -> str:
        return "mock"

    @property
    def is_running(self) -> bool:
        return self._running

    async def execute(
        self,
        context_file: str,
        working_dir: str | None = None
    ) -> AgentResult:
        """
        Simulate task execution.

        :param context_file: Path to the task context file
        :param working_dir: Working directory for the agent
        :return: AgentResult with mock results
        """
        self._running = True
        self.logger.info(f"[Mock] Starting execution with context: {context_file}")

        try:
            # Read context file
            context_path = Path(context_file)
            if not context_path.exists():
                return AgentResult(
                    success=False,
                    error=f"Context file not found: {context_file}"
                )

            context = context_path.read_text(encoding="utf-8")

            # Simulate processing time
            await asyncio.sleep(self.delay)

            # Extract output file requirement from context
            output_file = None
            for line in context.split("\n"):
                if "输出文件：" in line:
                    # Extract path after "输出文件："
                    parts = line.split("输出文件：")
                    if len(parts) > 1:
                        output_file = parts[1].strip()
                        break

            # Create mock output if output file is specified
            output_files = []
            if output_file:
                output_path = Path(output_file)
                output_path.parent.mkdir(parents=True, exist_ok=True)

                mock_content = f"""# Mock Output

This is a mock output generated by the MockAdapter for testing purposes.

## Task Context Summary

The task was read from: {context_file}

## Mock Result

Task executed successfully (simulated).

<!-- TASK_COMPLETED -->
"""
                output_path.write_text(mock_content, encoding="utf-8")
                output_files.append(str(output_path))
                self.logger.info(f"[Mock] Created output file: {output_path}")

            self._running = False
            self.logger.info("[Mock] Execution completed")

            return AgentResult(
                success=True,
                output="Mock execution completed successfully",
                output_files=output_files
            )

        except Exception as e:
            self._running = False
            self.logger.error(f"[Mock] Execution failed: {str(e)}")
            return AgentResult(
                success=False,
                error=str(e)
            )

    async def stop(self) -> None:
        """Stop the current execution."""
        self._running = False
        self.logger.info("[Mock] Execution stop requested")
